#!/usr/bin/env bash

link_paths=(
  button
  card
  dropdown
  field
  icon
  input/checkbox
  input/radio
  input/textbox
  menu
  modal
  popover
  portal
  progressindicators/CircleIndicator.scala
  progressindicators/BarIndicator.scala
  progressindicators/BlockIndicator.scala
  stepper
  tab/Tab.scala
  tab/TabFull.scala
  table
  tag
  toggle
  tooltip
  truncate
  util/ComponentUtils.scala
  util/EventUtils.scala
  util/NodeListSeq.scala
  well
)
